version: '3.6'
services:
  # Backend API
  smart-brain-api:
    container_name: backend
    #image: node:8.11.1
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_USER: vaibhav
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
      POSTGRES_URI: postgres://vaibhav:secret@postgres:5432/smartBrain
      REDIS_URI: redis://redis:6379

    links:
      - 'postgres'
      - 'redis'
    ports:
      - '6000:6000'
    volumes:
      - ./:/usr/src/smart-brain-api

  #Smart-Brain-Client
  # Postgres
  postgres:
    #container_name: postgres
    environment:
      POSTGRES_USER: vaibhav
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smartBrain
      POSTGRES_HOST: postgres
      POSTGRES_URL: postgres://vaibhav:secret@localhost:5432/smartBrain
    build: ./postgres
    ports:
      - '5432:5432'
  #REDIS
  redis:
    image: redis
    ports:
      - '6379:6379'
